Csr 10
FedAGcom/CSR_back pull request #8
Opened 2022-09-03 14:56 UTC by gamakarenko

2022-09-03 16:35 UTC, Aleksandr-Gurin requested changes

2022-09-03 16:35 UTC, Aleksandr-Gurin commented on src/main/java/com/fedag/CSR/repository/PackRepository.java
> +public interface PackRepository extends JpaRepository<Pack, BigDecimal> {
Давай добавим аннотацию @Repository

2022-09-03 19:53 UTC, gamakarenko commented on src/main/java/com/fedag/CSR/repository/PackRepository.java
> +public interface PackRepository extends JpaRepository<Pack, BigDecimal> {
Добавил

2022-09-04 09:02 UTC, Aleksandr-Gurin approved these changes

2022-09-04 09:03 UTC, merged